const IMAGE = {
    ICON_PROFILE: require('../images/user.png'),
    ICON_BACK: require('../images/back.png'),
    ICON_HOME: require('../images/home.png'),
    ICON_HOME_BLACK: require('../images/home-black.png'),
    ICON_SETTINGS: require('../images/settings.png'),
    ICON_SETTINGS_BLACK: require('../images/settings-black.png'),
    ICON_SEARCH: require('../images/search.png'),
    ICON_SEARCH_BLACK: require('../images/search-black.png'),
    ICON_WELCOME: require('../images/welcome.jpg'),
    ICON_LOGIN: require('../images/login.png'),
    ICON_MENU: require('../images/open-menu.png'),
    ICON_GO2: require('../images/lets-go2.png'),
    ICON_REGISTER: require('../images/register.png'),
    ICON_LOGOUT: require('../images/logout.png'),
    ICON_GIRL: require('../images/girl.png'),
    ICON_BOOKMARK: require('../images/bookmark.png'),
    ICON_BOOKMARK_BLACK: require('../images/bookmark-black.png'),
    ICON_BOOKMARK_ADD: require('../images/bookmark-add.png'),
    ICON_BOOKMARK_REMOVE: require('../images/bookmark-remove.png'),
}
export { IMAGE }